### PR TITLE
Adjust user attendance list

### PR DESCRIPTION
**Pull request by pratanothayanon97**
- Update account page to have the same recent event attended list
- Sort attendees list by roles (Admin appears at the top)

### CODE REVIEW

**Review by amaredia3 — APPROVED** [review]
Changes look good.

Code follows coding conventions.
Adds admins to ranking table.


Small note: was attendance_id not an attribute in user entity before?

**Comment by pratanothayanon97** [comment]
> Changes look good.
> 
> Code follows coding conventions. Adds admins to ranking table.
> 
> Small note: was attendance_id not an attribute in user entity before?

You made a good point Asim. I don't think attendance_id exists in user model if you look at the data design. What are your thoughts?

**Comment by amaredia3** [comment]
> > Changes look good.
> > Code follows coding conventions. Adds admins to ranking table.
> > Small note: was attendance_id not an attribute in user entity before?
> 
> You made a good point Asim. I don't think attendance_id exists in user model if you look at the data design. What are your thoughts?

According to the data design, attendance entity has a user_id attribute to help up link users to attendance. Attendance_id is not present in user entity.

**Comment by amaredia3** [comment]
> > > Changes look good.
> > > Code follows coding conventions. Adds admins to ranking table.
> > > Small note: was attendance_id not an attribute in user entity before?
> > 
> > 
> > You made a good point Asim. I don't think attendance_id exists in user model if you look at the data design. What are your thoughts?
> 
> According to the data design, attendance entity has a user_id attribute to help up link users to attendance. Attendance_id is not present in user entity.

If its needed we can leave it at this point.

**Comment by pratanothayanon97** [comment]
> > > > Changes look good.
> > > > Code follows coding conventions. Adds admins to ranking table.
> > > > Small note: was attendance_id not an attribute in user entity before?
> > > 
> > > 
> > > You made a good point Asim. I don't think attendance_id exists in user model if you look at the data design. What are your thoughts?
> > 
> > 
> > According to the data design, attendance entity has a user_id attribute to help up link users to attendance. Attendance_id is not present in user entity.
> 
> If its needed we can leave it at this point.

I think you may misunderstand it because I have not done anything with attendance_id attribute. I added has_many attendances because user has many attendances. I had been trying to join user with attendance, but it failed because the relationship between user and attendance was not created in the model at the first place.

**Comment by amaredia3** [comment]
> > > > > Changes look good.
> > > > > Code follows coding conventions. Adds admins to ranking table.
> > > > > Small note: was attendance_id not an attribute in user entity before?
> > > > 
> > > > 
> > > > You made a good point Asim. I don't think attendance_id exists in user model if you look at the data design. What are your thoughts?
> > > 
> > > 
> > > According to the data design, attendance entity has a user_id attribute to help up link users to attendance. Attendance_id is not present in user entity.
> > 
> > 
> > If its needed we can leave it at this point.
> 
> I think you may misunderstand it because I have not done anything with attendance_id attribute. I added has_many attendances because user has many attendances. I had been trying to join user with attendance, but it failed because the relationship between user and attendance was not created in the model at the first place.

Oh ok. Sounds good.

**Pull request merged**
