### PR TITLE
fixing edit user points form and rank button

### PR DESCRIPTION
**Pull request by amaredia3**
Old
Image 11-13-22 at 10 13 AM (1)
New
Image 11-13-22 at 10 13 AM

### CODE REVIEW

**Review by jesicaj99 — APPROVED** [review]
There is an issue with the table container showing white space and ranking button giving error

**Review by pratanothayanon97 — CHANGES_REQUESTED** [review]
I check your branch and it works fine on mobile, however, the alignment of table is not right on my end for normal view. Does this happen to you as well, or just me? 
asim_branch

**Comment by amaredia3** [comment]
> I check your branch and it works fine on mobile, however, the alignment of table is not right on my end for normal view. Does this happen to you as well, or just me?
> asim_branch

Fixed in new commit. See branch deployed to heroku for latest changes.

**Comment by amaredia3** [comment]
> There is an issue with the table container showing white space and ranking button giving error

Pushed the fix for it. Table now covers the page and rank button works.

**Review by jesicaj99 — COMMENTED** [review]
Ranking button still has error in the Heroku deployment

**Comment by amaredia3** [comment]
> Ranking button still has error and edit takes user to new page instead

Are you testing this in the Heroku review app. It's working fine for me there.

**Comment by amaredia3** [comment]
Updated PR:

Removed rank button:
    Caused errors with certain browser settings.
    Removing it does not violate nay acceptance criteria or scope items (admin can view users ranked by points in ranking     page).

**Review by pratanothayanon97 — APPROVED** [review]

**Pull request merged**
